
---
notifications:
  email: false
language: ruby
rvm:
  - 1.9.3
  - 2.1
  - 2.3
  - 2.4
cache: bundler
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.0.1" STRICT_VARIABLES=yes
matrix:
  fast_finish: true
  exclude:
  # exclude all puppet 4.x 5.x for ruby 1.9.3
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 5.0.1" STRICT_VARIABLES=yes
  - rvm: 2.3
    env: PUPPET_GEM_VERSION="~> 5.0.1" STRICT_VARIABLES=yes
  # eclude all puppet 3.x 4.x for ruby 2.4
  - rvm: 2.4
    env: PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - rvm: 2.4
    env: PUPPET_GEM_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - rvm: 2.4
    env: PUPPET_GEM_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
